artifacts:
    raw_data_path: "./data/raw/"
    processed_data_path: "./data/processed/"
    checkpoints: "./artifacts/checkpoints/"
    train_models: "./artifacts/checkpoints/train_models/"
    best_model: "./artifacts/checkpoints/best_model/"
    files: "./artifacts/files/"
    metrics: "./artifacts/metrics/"
    train_images: "./artifacts/outputs/train_images/"
    val_images: "./artifacts/outputs/val_images/"
    test_image: "./artifacts/outputs/test_image/"

patchEmbeddings:
    channels: 3
    patch_size: 16
    image_size: 224
    dimension: 256

transfomerEncoderBlock:
    nheads: 8
    activation: "leaky"
    dropout: 0.1
    num_encoder_layers: 6
    dimension_feedforward: 4096
    layer_norm_eps: 1e-5

dataloader:
    dataset: "./raw/image_dataset.zip"
    batch_size: 32
    split_size: 0.30
    
trainer:
    model: None
    epochs: 200
    lr: 2e-4
    weight_decay: 5e-4
    beta1: 0.9
    beta2: 0.999
    momentum: 0.95
    lr_scheduler: False
    step_size: 20
    gamma: 0.1
    l1_regularization: False
    l2_regularization: False
    l1_lambda: 0.0
    l2_lambda: 0.0
    adam: True
    SGD: False
    mlflow: False
    verbose: False
    device: "mps"

tester:
    model: "best"
    device: "mps"
    plot_images: True